FROM node:18-slim
RUN npm install -g npm
WORKDIR /home/node/app
COPY package*.json ./
RUN npm install
COPY startup.sh ./startup.sh
RUN chmod +x ./startup.sh
ENV PORT=4000
EXPOSE 4000
# RUN rm -rf build
# RUN mkdir build && chown node:node build
USER node
CMD sh -c "npm run build && npm run start"
