version: "3"
services:
  client:
    build:
      context: ./client
      dockerfile: ../Dockerfile.client
    volumes:
      - ./client:/home/node/app
      - /home/node/app/node_modules
    ports:
      - 3000:3000
  server:
    build:
      context: ./server
      dockerfile: ../Dockerfile.server
    volumes:
      - ./server:/app
      - /app/node_modules
    ports:
      - 8000:8000
